version: '3.7'

services:
  discovery-service:
    image: swp490-discovery-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8762:8762"
    networks:
      - currency-network
  config-server:
    image: config-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8334:8334"
    networks:
      - currency-network
    depends_on:
      - discovery-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-service:8762/eureka
      SPRING.CLOUD.CONFIG.SERVER.GIT.URI: https://github.com/he141142/config-repo.git
      SPRING.CLOUD.CONFIG.SERVER.GIT.TIMEOUT: 10
      SPRING.CLOUD.CONFIG.SERVER.DEFAULT-LABEL: main
      SPRING.CLOUD.CONFIG.SERVER.FORCE-PULL: true
  flashcard-service:
    image: swp490-flash-card-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8096:8096"
    networks:
      - currency-network
    depends_on:
      - config-server
      - flashcarddb
    environment:
      SPRING.CLOUD.CONFIG.URI: http://config-server:8334
      SPRING.CONFIG.IMPORT: optional:configserver:http://config-server:8334
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-service:8762/eureka

  flashcarddb:
    image: postgres@sha256:2c1fb5ffd530cd8d7935ff71959dc548f83763b7c29038d62706b15e58a44285
    restart: always
    ports:
      - '9006:5432'
    environment:
      POSTGRES_PASSWORD: fqQ3nN4L
      POSTGRES_USER: sykros
      POSTGRES_DB: flashcard
    volumes:
      - D:/swp490/database/flashcardservice:/var/lib/postgresql/data
    networks:
      - currency-network

  userdb:
    image: postgres@sha256:2c1fb5ffd530cd8d7935ff71959dc548f83763b7c29038d62706b15e58a44285
    restart: always
    ports:
      - '9003:5432'
    environment:
      POSTGRES_PASSWORD: fqQ3nN4L
      POSTGRES_USER: sykros
      POSTGRES_DB: user-data
    volumes:
      - D:/swp490/database/userservice:/var/lib/postgresql/data
    networks:
      - currency-network

  user-service:
    image: user-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8777:8777"
    networks:
      - currency-network
    depends_on:
      - config-server
      - discovery-service
      - userdb
    environment:
      SPRING.CLOUD.CONFIG.URI: http://config-server:8334
      SPRING.CONFIG.IMPORT: optional:configserver:http://config-server:8334
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-service:8762/eureka
      SPRING.CLOUD.CONFIG.LABEL: prod


  gateway:
    image: api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "9733:9733"
    networks:
      - currency-network
    depends_on:
      - config-server
      - discovery-service
    environment:
#      SPRING.CLOUD.CONFIG.URI: http://config-server:8334
#      SPRING.CONFIG.IMPORT: optional:configserver:http://config-server:8334
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-service:8762/eureka
#      SPRING.CLOUD.CONFIG.LABEL: prod

  auth-service:
    image: auth-service:0.0.1-SNAPSHOT
    depends_on:
      - keycloak
      - config-server
    ports:
      - "8778:8778"
    networks:
      - currency-network
    environment:
      SPRING.CLOUD.CONFIG.URI: http://config-server:8334
      SPRING.CONFIG.IMPORT: optional:configserver:http://config-server:8334
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-service:8762/eureka
      SPRING.CLOUD.CONFIG.LABEL: prod

  dbpostgres:
    image: postgres@sha256:2c1fb5ffd530cd8d7935ff71959dc548f83763b7c29038d62706b15e58a44285
    container_name: quizferdb
    restart: always
    ports:
      - '9002:5432'
    environment:
      POSTGRES_PASSWORD: fqQ3nN4L
      POSTGRES_USER: sykros
      POSTGRES_MULTIBLE_DATABASES: quizfer
    volumes:
      - D:/swp490/quizfer/backup:/var/lib/postgresql/data
    networks:
      - currency-network

  keycloak:
    image: quay.io/keycloak/keycloak:10.0.1
    mem_limit: 1000m
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: postgres
      DB_ADDR: quizferdb
      DB_DATABASE: keycloak
      DB_USER: sykros
      DB_SCHEMA: public
      DB_PASSWORD: fqQ3nN4L
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JDBC_PARAMS: useSSL=false&allowPublicKeyRetrieval=true

    ports:
      - 9028:8080
    depends_on:
      - dbpostgres
    networks:
      - currency-network

networks:
  currency-network:
