
spring:
  profiles:
    include:
      - dev
  datasource:
    url: jdbc:postgresql://localhost:3933/flashcard
    username: sykros
    password: fqQ3nN4L
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        current_session_context_class: thread
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 400
        order_inserts: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true


eureka:
  instance:
    appname: flashcard-service
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #    hostname: user-service
  #    homePageUrl: http://${eureka.hostname}/
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka