spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9028/auth/realms/oauth2-quizfer
          jwk-set-uri: http://localhost:9028/auth/realms/oauth2-quizfer/protocol/openid-connect/certs
  profiles:
    include:
      - dev
  datasource:
    url: jdbc:postgresql://flashcarddb:5432/flashcard
    username: sykros
    password: fqQ3nN4L
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        current_session_context_class: thread
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 400
        order_inserts: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true


eureka:
  instance:
    appname: flashcard-service
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka

feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      DemoClientgetDemo:
        minimumNumberOfCalls: 69
  timelimiter:
    instances:
      DemoClientgetDemo:
        timeoutDuration: 10s

keycloak-admin:
  username: admindeptrai
  password: admin123