spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/oauth2-quizfer
          jwk-set-uri: http://keycloak:8080/auth/realms/oauth2-quizfer/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://userdb:5432/user-data
    username: sykros
    password: fqQ3nN4L
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        current_session_context_class: thread
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    servlet:
      multipart:
        enabled: true
keycloak-admin:
  username: admindeptrai
  password: admin123