spring:
  datasource:
    url: jdbc:postgresql://userservice:5432/user-data
    username: sykros
    password: fqQ3nN4L
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        current_session_context_class: thread
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    servlet:
      multipart:
        enabled: true